version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.15"
  commands:
    - python -m pip install uv==0.13.0
    - python -m uv tool install tox==4.64.7 --with tox-uv==1.36.1 -p 3.15 --managed-python
    - ~/.local/bin/tox run -e docs --
