from __future__ import annotations

from itertools import chain, combinations
from typing import TYPE_CHECKING, Final

import pytest

from bump_deps_index import main

if TYPE_CHECKING:
    from pathlib import Path

    from conftest import FakeIndex

pytestmark = pytest.mark.usefixtures("isolated_index_settings")

_FILES: Final[dict[str, str]] = {
    "pyproject.toml": '[project]\ndependencies = ["foo>=1"]\n',
    "tox.toml": 'requires = ["foo>=1"]\n',
    "tox.ini": "[tox]\nrequires = foo>=1\n",
    ".pre-commit-config.yaml": (
        "repos:\n- repo: local\n  hooks:\n  - id: a\n    language: python\n    additional_dependencies: [foo>=1]\n"
    ),
    "setup.cfg": "[options]\ninstall_requires = foo>=1\n",
}


@pytest.fixture
def project(index: FakeIndex, monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Path:
    index.pypi["foo"] = ["2"]
    monkeypatch.chdir(tmp_path)
    return tmp_path


@pytest.mark.parametrize(
    "names",
    [
        pytest.param(set(combo), id="+".join(sorted(combo)))
        for combo in chain.from_iterable(combinations(_FILES, size) for size in range(1, len(_FILES) + 1))
    ],
)
def test_cli_updates_the_files_it_finds(index: FakeIndex, project: Path, names: set[str]) -> None:
    for name in names:
        (project / name).write_text(_FILES[name], encoding="utf-8")
    (project / "decoy").write_text("foo>=1\n", encoding="utf-8")

    main(["-i", index.index_url])

    assert {path.name for path in project.iterdir() if "foo>=2" in path.read_text(encoding="utf-8")} == names


def test_cli_updates_only_the_files_you_name(index: FakeIndex, project: Path) -> None:
    for name in ("pyproject.toml", "setup.cfg"):
        (project / name).write_text(_FILES[name], encoding="utf-8")

    main(["-i", index.index_url, "-f", "pyproject.toml"])

    assert [(project / name).read_text(encoding="utf-8") for name in ("pyproject.toml", "setup.cfg")] == [
        _FILES["pyproject.toml"].replace("foo>=1", "foo>=2"),
        _FILES["setup.cfg"],
    ]


def test_cli_skips_generated_requirements(capsys: pytest.CaptureFixture[str], index: FakeIndex, project: Path) -> None:
    content = "# This file was autogenerated by pip-compile\nfoo>=1\n"
    (project / "requirements.txt").write_text(content, encoding="utf-8")

    with pytest.raises(SystemExit):
        main(["-i", index.index_url])

    assert (capsys.readouterr().err, (project / "requirements.txt").read_text(encoding="utf-8")) == (
        "no supported dependency files found\n",
        content,
    )


def test_cli_skips_file_discovery_for_packages(
    capsys: pytest.CaptureFixture[str], index: FakeIndex, project: Path
) -> None:
    (project / "pyproject.toml").write_text(_FILES["pyproject.toml"], encoding="utf-8")

    main(["-i", index.index_url, "foo"])

    assert (capsys.readouterr().out.splitlines()[-1], (project / "pyproject.toml").read_text(encoding="utf-8")) == (
        "foo -> foo>=2",
        _FILES["pyproject.toml"],
    )


def test_cli_accepts_pre_releases_in_pre_commit_only_by_default(index: FakeIndex, project: Path) -> None:
    index.pypi["foo"] = ["1", "2b1"]
    for name in (".pre-commit-config.yaml", "setup.cfg"):
        (project / name).write_text(_FILES[name], encoding="utf-8")

    main(["-i", index.index_url])

    assert [(project / name).read_text(encoding="utf-8") for name in (".pre-commit-config.yaml", "setup.cfg")] == [
        _FILES[".pre-commit-config.yaml"].replace("foo>=1", "foo>=2b1"),
        _FILES["setup.cfg"],
    ]


def test_cli_redacts_credentials_in_help(capsys: pytest.CaptureFixture[str], monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("PIP_INDEX_URL", "https://user:secret@index.example/simple")

    with pytest.raises(SystemExit) as error:
        main(["--help"])

    output = capsys.readouterr().out
    assert (error.value.code, "secret" in output, "https://index.example/simple" in output) == (0, False, True)
