from __future__ import annotations

from itertools import accumulate
from pathlib import Path
from typing import TYPE_CHECKING, ClassVar

from bump_deps_index._spec import PkgType

from ._base import Loader

if TYPE_CHECKING:
    from collections.abc import Iterator, Mapping

    from ._base import Entry


class Requirements(Loader):
    _bases: ClassVar[frozenset[str]] = frozenset({"requirements", "constraints"})

    @staticmethod
    def supports(filename: Path) -> bool:
        return filename.suffix in {".in", ".txt"} and not (
            filename.suffix == ".txt" and filename.with_suffix(".in").exists()
        )

    def _update_text(self, text: str, changes: Mapping[str, str]) -> str:
        lines = text.split("\n")
        for entry in self._entries(lines):
            logical = " ".join(segment for _, segment in entry)
            if (new := changes.get(logical, logical)) == logical:
                continue
            # find the edited span to rewrite the physical line holding it in a `\`-continued requirement
            start = _common_prefix(logical, new)
            kept = _common_prefix(logical[start:][::-1], new[start:][::-1])
            offsets = accumulate((len(segment) + 1 for _, segment in entry), initial=0)
            at, segment, offset = next(
                (at, segment, offset)
                for (at, segment), offset in zip(entry, offsets, strict=False)
                if offset <= start and len(logical) - kept <= offset + len(segment)
            )
            edited = (
                f"{segment[: start - offset]}{new[start : len(new) - kept]}{segment[len(logical) - kept - offset :]}"
            )
            lines[at] = self._replace_requirement_line(lines[at], {segment: edited})
        return "\n".join(lines)

    @property
    def files(self) -> Iterator[Path]:
        generated_marker = "# This file was autogenerated by"
        found = {
            f
            for f in Path.cwd().iterdir()
            if (f.stem.split(".")[0] in self._bases or f.stem.split("-")[0] in self._bases)
            and f.suffix in {".in", ".txt"}
        }
        existing_names = {f.name for f in found}

        for filename in found:
            if filename.suffix == ".txt" and filename.with_suffix(".in").name in existing_names:
                continue
            with filename.open("rt", encoding="utf-8") as file_handler:
                for line in file_handler:
                    if line.startswith(generated_marker):
                        break
                else:
                    yield filename

    def load(self, filename: Path, *, pre_release: bool | None) -> Iterator[Entry]:
        lines = filename.read_text(encoding="utf-8").split("\n")
        requirements = [" ".join(segment for _, segment in entry) for entry in self._entries(lines)]
        yield from self._generate(
            requirements, pkg_type=PkgType.PYTHON, pre_release=False if pre_release is None else pre_release
        )

    @classmethod
    def _entries(cls, lines: list[str]) -> Iterator[list[tuple[int, str]]]:
        entry: list[tuple[int, str]] = []
        for at, line in enumerate(lines):
            stripped, _ = cls._split_comment(line.strip())
            entry.append((at, stripped.removesuffix("\\").rstrip()))
            if stripped.endswith("\\"):
                continue
            logical = " ".join(segment for _, segment in entry)
            # skip hashed entries; you would need new hashes for a new version
            if logical and not logical.startswith(("#", "-")) and "--hash" not in logical:
                yield entry
            entry = []


def _common_prefix(left: str, right: str) -> int:
    return next(
        (at for at, (first, second) in enumerate(zip(left, right, strict=False)) if first != second),
        min(len(left), len(right)),
    )


__all__ = [
    "Requirements",
]
