from __future__ import annotations

import re
import shlex
from itertools import accumulate
from pathlib import Path
from typing import TYPE_CHECKING, ClassVar, Final

from bump_deps_index._parsed import expand_env
from bump_deps_index._spec import PkgType

from ._base import Entry, Loader

if TYPE_CHECKING:
    from collections.abc import Iterator, Mapping

_OPTIONS: Final[dict[str, str]] = {
    "-i": "index",
    "--index-url": "index",
    "-r": "include",
    "--requirement": "include",
    "-c": "include",
    "--constraint": "include",
}


class Requirements(Loader):
    _bases: ClassVar[tuple[str, ...]] = ("requirements", "constraints")

    @staticmethod
    def supports(filename: Path) -> bool:
        return filename.suffix in {".in", ".txt"} and not (
            filename.suffix == ".txt" and filename.with_suffix(".in").exists()
        )

    def _update_text(self, text: str, changes: Mapping[str, str]) -> str:
        lines = text.split("\n")
        for entry in self._entries(lines):
            logical = " ".join(segment for _, segment in entry)
            if (new := changes.get(logical, logical)) == logical:
                continue
            # find the edited span to rewrite the physical line holding it in a `\`-continued requirement
            start = _common_prefix(logical, new)
            kept = _common_prefix(logical[start:][::-1], new[start:][::-1])
            offsets = accumulate((len(segment) + 1 for _, segment in entry), initial=0)
            at, segment, offset = next(
                (at, segment, offset)
                for (at, segment), offset in zip(entry, offsets, strict=False)
                if offset <= start and len(logical) - kept <= offset + len(segment)
            )
            edited = (
                f"{segment[: start - offset]}{new[start : len(new) - kept]}{segment[len(logical) - kept - offset :]}"
            )
            lines[at] = self._replace_requirement_line(lines[at], {segment: edited})
        return "\n".join(lines)

    @property
    def files(self) -> Iterator[Path]:
        generated_marker = "# This file was autogenerated by"
        found = {f for f in Path.cwd().iterdir() if f.stem.startswith(self._bases) and f.suffix in {".in", ".txt"}}
        existing_names = {f.name for f in found}

        for filename in found:
            if filename.suffix == ".txt" and filename.with_suffix(".in").name in existing_names:
                continue
            with filename.open("rt", encoding="utf-8") as file_handler:
                for line in file_handler:
                    if line.startswith(generated_marker):
                        break
                else:
                    yield filename

    def load(self, filename: Path, *, pre_release: bool | None) -> Iterator[Entry]:
        lines = filename.read_text(encoding="utf-8").split("\n")
        requirements = [" ".join(segment for _, segment in entry) for entry in self._entries(lines)]
        index_url = self._index_url(filename, set())
        for requirement in requirements:
            yield Entry(requirement, PkgType.PYTHON, False if pre_release is None else pre_release, index_url=index_url)

    @classmethod
    def _index_url(cls, filename: Path, seen: set[Path]) -> str | None:
        # pip applies the last `--index-url` it reads, including those in files that `-r` or `-c` pulls in
        seen.add(filename.resolve())
        try:
            lines = filename.read_text(encoding="utf-8").splitlines()
        except (OSError, UnicodeDecodeError):
            return None
        found = None
        # pip joins `\`-continued lines, then splits each line into shell words before it reads the options
        for line in re.sub(r"\\\n", " ", "\n".join(lines)).split("\n"):
            try:
                words = shlex.split(cls._split_comment(line.strip())[0])
            except ValueError:
                continue
            for name, value in _options(words):
                if name == "index":
                    found = expand_env(value)
                elif (included := filename.parent / expand_env(value)).resolve() not in seen:
                    found = cls._index_url(included, seen) or found
        return found

    @classmethod
    def _entries(cls, lines: list[str]) -> Iterator[list[tuple[int, str]]]:
        entry: list[tuple[int, str]] = []
        for at, line in enumerate(lines):
            # pip drops a comment line inside a `\`-continued requirement
            stripped = "" if line.lstrip().startswith("#") else cls._split_comment(line.strip())[0]
            if segment := stripped.removesuffix("\\").rstrip():
                entry.append((at, segment))
            if stripped.endswith("\\"):
                continue
            logical = " ".join(segment for _, segment in entry)
            # skip hashed entries; you would need new hashes for a new version
            if logical and not logical.startswith("-") and "--hash" not in logical:
                yield entry
            entry = []


def _options(words: list[str]) -> Iterator[tuple[str, str]]:
    for at, word in enumerate(words):
        name, equals, value = word.partition("=")
        if name in _OPTIONS and equals:
            yield _OPTIONS[name], value
        elif word in _OPTIONS and at + 1 < len(words):
            yield _OPTIONS[word], words[at + 1]
        elif word[:2] in {"-i", "-r", "-c"} and len(word) > len("-i"):
            yield _OPTIONS[word[:2]], word[2:]


def _common_prefix(left: str, right: str) -> int:
    return next(
        (at for at, (first, second) in enumerate(zip(left, right, strict=False)) if first != second),
        min(len(left), len(right)),
    )


__all__ = [
    "Requirements",
]
