from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, ClassVar

from bump_deps_index._spec import PkgType

from ._base import Loader

if TYPE_CHECKING:
    from collections.abc import Iterator, Mapping


class Requirements(Loader):
    _base: ClassVar[str] = "requirements"

    def supports(self, filename: Path) -> bool:
        return (
            filename.suffix in {".in", ".txt"}
            and (filename.stem.split(".")[0] == self._base or filename.stem.split("-")[0] == self._base)
            and not (filename.suffix == ".txt" and filename.with_suffix(".in").exists())
        )

    def update_file(self, filename: Path, changes: Mapping[str, str]) -> None:
        lines = filename.read_text(encoding="utf-8").split("\n")
        result = [
            self._replace_requirement_line(line, changes)
            if line.strip() and not line.strip().startswith(("#", "-"))
            else line
            for line in lines
        ]
        filename.write_text("\n".join(result), encoding="utf-8")

    @property
    def files(self) -> Iterator[Path]:
        generated_marker = "# This file was autogenerated by"
        found = {
            f
            for f in Path.cwd().iterdir()
            if (f.stem.split(".")[0] == self._base or f.stem.split("-")[0] == self._base)
            and f.suffix in {".in", ".txt"}
        }
        existing_names = {f.name for f in found}

        for filename in found:
            if filename.suffix == ".txt" and filename.with_suffix(".in").name in existing_names:
                continue
            with filename.open("rt", encoding="utf-8") as file_handler:
                for line in file_handler:
                    if line.startswith(generated_marker):
                        break
                else:
                    yield filename

    def load(self, filename: Path, *, pre_release: bool | None) -> Iterator[tuple[str, PkgType, bool]]:
        pre = False if pre_release is None else pre_release
        lines = []
        for line in filename.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped and not stripped.startswith(("#", "-")):
                requirement, _ = self._split_comment(stripped)
                lines.append(requirement.removesuffix("\\").rstrip())
        yield from self._generate(lines, pkg_type=PkgType.PYTHON, pre_release=pre)


__all__ = [
    "Requirements",
]
